# Generated by Django 5.0.7 on 2025-01-26 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PositionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان")),
                ("code", models.CharField(max_length=255, verbose_name="کد")),
                ("level", models.IntegerField(default=0, verbose_name="سطح")),
            ],
            options={
                "verbose_name": "نوع پست سازمانی",
                "verbose_name_plural": "انواع پست های سازمانی",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Telephone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "extension",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="افزونه"
                    ),
                ),
                (
                    "complete_number",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="تلفن کامل"
                    ),
                ),
                (
                    "tel_address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="آدرس"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="توضیحات"
                    ),
                ),
            ],
            options={
                "verbose_name": "تلفن داخلی",
                "verbose_name_plural": "تلفن\u200cهای داخلی",
                "ordering": ["extension", "complete_number"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dep_title",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("معاونت", "معاونت"),
                            ("مدیریت", "مدیریت"),
                            ("دانشکده", "دانشکده"),
                            ("گروه", "گروه"),
                            ("اداره", "اداره"),
                            ("دبیرخانه", "دبیرخانه"),
                            ("حوزه", "حوزه"),
                            ("مرکز", "مرکز"),
                            ("کمیته", "کمیته"),
                            ("شورا", "شورا"),
                            ("سرای", "سرای دانشجوی"),
                            ("گیت", "گیت"),
                        ],
                        max_length=255,
                        null=True,
                        verbose_name="عنوان",
                    ),
                ),
                ("dep_name", models.CharField(max_length=255, verbose_name="نام")),
                (
                    "dep_address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="آدرس"
                    ),
                ),
                ("level", models.IntegerField(default=0, verbose_name="سطح")),
                (
                    "super_dep",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="telephones.department",
                        verbose_name="واحد های مرتبط",
                    ),
                ),
            ],
            options={
                "verbose_name": "واحد سازمانی",
                "verbose_name_plural": "واحدهای سازمانی",
                "ordering": ["dep_title", "dep_name"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pic",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images",
                        verbose_name="عکس پروفایل",
                    ),
                ),
                ("first_name", models.CharField(max_length=255, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=255, verbose_name="نام خانوادگی"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "مرد"), ("F", "زن")],
                        default="M",
                        max_length=1,
                        verbose_name="جنسیت",
                    ),
                ),
                (
                    "birthday",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ تولد"),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        unique=True,
                        verbose_name="کدملی",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="ایمیل"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="تلفن همراه"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حساب کاربری",
                    ),
                ),
            ],
            options={
                "verbose_name": "کاربر",
                "verbose_name_plural": "کاربران",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duties",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="وظایف",
                    ),
                ),
                (
                    "dep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deps",
                        to="telephones.department",
                        verbose_name="واحد سازمانی",
                    ),
                ),
                (
                    "position_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="position_types",
                        to="telephones.positiontype",
                        verbose_name="نوع پست سازمانی",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owners",
                        to="telephones.profile",
                        verbose_name="کاربر مسئول",
                    ),
                ),
            ],
            options={
                "verbose_name": "پست سازمانی",
                "verbose_name_plural": "پست\u200cهای سازمانی",
                "ordering": ["dep", "position_type", "owner"],
            },
        ),
        migrations.CreateModel(
            name="Assign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ تخصیص"),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="telephones.position",
                        verbose_name="پست سازمانی",
                    ),
                ),
                (
                    "tel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tels",
                        to="telephones.telephone",
                        verbose_name="شماره تلفن",
                    ),
                ),
            ],
            options={
                "verbose_name": "تخصیص تلفن",
                "verbose_name_plural": "تخصیص تلفن\u200cها",
                "ordering": ["position", "tel"],
            },
        ),
    ]
