# Generated by Django 3.2.25 on 2024-06-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephones', '0014_auto_20240628_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='عکس پروفایل'),
        ),
    ]
