# Generated by Django 3.2.25 on 2024-06-29 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telephones', '0017_auto_20240629_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name', 'title'], 'verbose_name': 'واحد سازمانی', 'verbose_name_plural': 'واحدهای سازمانی'},
        ),
        migrations.RenameField(
            model_name='department',
            old_name='dep_title',
            new_name='title',
        ),
    ]
