# Generated by Django 3.2.25 on 2024-06-29 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telephones', '0018_auto_20240629_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dep_address',
            new_name='address',
        ),
    ]
