# Generated by Django 3.2.25 on 2024-06-29 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telephones', '0019_rename_dep_address_department_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='department',
            name='level',
            field=models.IntegerField(default=0, verbose_name='سطح'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='department',
            name='super_dep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telephones.department', verbose_name='واحد های مرتبط'),
        ),
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(blank=True, choices=[('معاونت', 'معاونت'), ('مدیریت', 'مدیریت'), ('دانشکده', 'دانشکده'), ('گروه', 'گروه'), ('اداره', 'اداره'), ('دبیرخانه', 'دبیرخانه'), ('حوزه', 'حوزه'), ('مرکز', 'مرکز'), ('کمیته', 'کمیته'), ('شورا', 'شورا'), ('سرای', 'سرای دانشجوی'), ('گیت', 'گیت')], max_length=255, null=True, verbose_name='عنوان'),
        ),
    ]
