# Generated by Django 3.2.25 on 2024-06-29 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telephones', '0020_auto_20240629_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['title', 'name'], 'verbose_name': 'واحد سازمانی', 'verbose_name_plural': 'واحدهای سازمانی'},
        ),
    ]
