# Generated by Django 5.1.4 on 2024-12-27 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephones', '0021_alter_department_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assign',
            options={'ordering': ['position', 'tel'], 'verbose_name': 'تخصیص تلفن', 'verbose_name_plural': 'تخصیص تلفن\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['dep_title', 'name'], 'verbose_name': 'واحد سازمانی', 'verbose_name_plural': 'واحدهای سازمانی'},
        ),
        migrations.AlterModelOptions(
            name='telephone',
            options={'ordering': ['extension', 'complete_number'], 'verbose_name': 'تلفن داخلی', 'verbose_name_plural': 'تلفن\u200cهای داخلی'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.RenameField(
            model_name='department',
            old_name='title',
            new_name='dep_title',
        ),
        migrations.AlterField(
            model_name='assign',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تخصیص'),
        ),
        migrations.AlterField(
            model_name='assign',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='telephones.position', verbose_name='پست سازمانی'),
        ),
        migrations.AlterField(
            model_name='assign',
            name='tel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tels', to='telephones.telephone', verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='position',
            name='dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deps', to='telephones.department', verbose_name='واحد سازمانی'),
        ),
        migrations.AlterField(
            model_name='position',
            name='duties',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='وظایف'),
        ),
        migrations.AlterField(
            model_name='position',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='telephones.userprofile', verbose_name='کاربر مسئول'),
        ),
        migrations.AlterField(
            model_name='position',
            name='position_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_types', to='telephones.positiontype', verbose_name='نوع پست سازمانی'),
        ),
        migrations.AlterField(
            model_name='positiontype',
            name='code',
            field=models.CharField(max_length=255, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='positiontype',
            name='level',
            field=models.IntegerField(default=0, verbose_name='سطح'),
        ),
        migrations.AlterField(
            model_name='positiontype',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='complete_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='تلفن کامل'),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='extension',
            field=models.CharField(max_length=255, unique=True, verbose_name='افزونه'),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='tel_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس'),
        ),
    ]
