# Generated by Django 4.2.8 on 2025-01-14 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telephones', '0013_alter_assign_options_alter_department_options_and_more'),
        ('telephones', '0025_rename_userprofile_profile'),
    ]

    operations = [
    ]
