# Generated by Django 4.2.8 on 2025-01-24 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telephones', '0026_merge_20250114_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assign',
            options={'ordering': ['position', 'tel'], 'verbose_name': 'تخصیص تلفن', 'verbose_name_plural': 'تخصیص تلفن\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterModelOptions(
            name='telephone',
            options={'ordering': ['extension', 'complete_number'], 'verbose_name': 'تلفن داخلی', 'verbose_name_plural': 'تلفن\u200cهای داخلی'},
        ),
    ]
